# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "smartnoise-core-python" %}
{% set version = "v0.1.0-sn" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/smartnoise-core-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: cd0e26276b19c07a6bb2bb730aba01ccd1be7b2f613131394ca7305b50baca16

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - opendp
    - opendp.smartnoise
    - opendp.smartnoise.core
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/opendp/smartnoise-core-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This repository contains python bindings to the SmartNoise Core library and its underlying Rust binaries.
  description:
    Smartnoise-core library is a parent library that references this child library Smartnoise-core-python,
    an easy-to-use python library interface for building analyses.
  doc_url: https://opendp.github.io/smartnoise-core/doc/smartnoise_validator/docs/components/index.html
  dev_url: https://github.com/opendp/smartnoise-core-python

extra:
  recipe-maintainers:
    - mxr-conda
    - achangeo
    - oblute
